feat: add/update benchmark of loss prevention pipelines documentation and make targets
intel-retail/loss-prevention pull request #16
Opened 2024-11-01 18:07 UTC by jim-wang-intel

## PR Checklist

- [ ] Added label to the Pull Request for easier discoverability and search
- [ ] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/loss-prevention/blob/main/CONTRIBUTING.md
- [ ] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

- add benchmark documentation
- update make targets: benchmark, benchmark-stream-density to have the right parameters for running result outputs
- add make target: clean-benchmark-results to be easier for cleaning between new sets of benchmarks

## Issue this PR will close

close: **#15**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

- git clone this PR
- follow the instructions documented in benchmark.md
- you should be able to run the benchmark and see the results for both number of pipelines and stream density for loss prevention

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/loss-prevention )

2024-11-01 23:18 UTC, seanohair22 requested changes
On my run, I had to specify python3 in the make targets and in the benchmark-scripts target `init-packages` I had to force the packages to install with `--break-system-packages` since I am not using a venv...

2024-11-02 00:09 UTC, antoniomtz approved these changes
LGTM. Ran successfully

2024-11-04 15:14 UTC, jim-wang-intel commented
> On my run, I had to specify python3 in the make targets and in the benchmark-scripts target `init-packages` I had to force the packages to install with `--break-system-packages` since I am not using a venv...

Thanks @seanohair22 for letting us know: the existing documentation suggests we use vent [in Prerequisite section](https://github.com/intel-retail/documentation/blob/main/docs_src/performance-tools/benchmark.md#prerequisites); but that is a good testing for non-virtual env. Usually I would also suggest running in venv so that if somehow python is messed up, you are less miserable :-) .

2024-11-04 15:23 UTC, jim-wang-intel commented on benchmark.md
> +This comes handy when you want to have a new set of benchmark for different benchmark use cases like different pipelines or running duration.
thank Sean, all typos are fixed :-)

2024-11-04 15:39 UTC, brian-intel approved these changes

2024-11-05 17:31 UTC, seanohair22 approved these changes

2024-11-05 17:54 UTC, merged